general_settings:
  master_key: sk-123
  
model_list: 
  - model_name: glm4-flash 
    litellm_params: 
      model: openai/glm-4-flash
      api_base: https://open.bigmodel.cn/api/paas/v4/
      api_key: sk-1
  - model_name: glm4-flash 
    litellm_params: 
      model: openai/glm-4-flash
      api_base: https://open.bigmodel.cn/api/paas/v4/
      api_key: sk-2
  - model_name: qwen3-8b
    litellm_params: 
      model: openai/Qwen/Qwen3-8B
      api_base: https://api.siliconflow.cn/v1
      api_key: sk-3


